<a href="https://colab.research.google.com/github/codestates/ds-sc13x/blob/master/sc13x.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SC13x Linear Algebra

## 1. $\vec{c} \cdot \vec{d}$ 를 구해보세요. 이 두 개의 vector는 orthogonal 관계 (직교)에 있나요? 왜 그런가요? 왜 아닌가요?

\begin{align}
\vec{c} = \begin{bmatrix}3 & 7 & -2 & 12\end{bmatrix}
\qquad
\vec{d} = \begin{bmatrix}9 & -7 & 4 & 6\end{bmatrix}
\end{align}

In [13]:
import pandas as pd
import numpy as np
#내적이 0 이면 직교관계에 있음
c = np.array([3, 7, -2, 12])
d = np.array([9, -7, 4, 6])

c_d = (c * d).sum()
c_d

42

In [ ]:
#내적이 0아 아니이므로 직교관계가 아님

## 2. $E^{-1}$ 와 $E^{T}$ 를 구하세요.

\begin{align}
E = 
\begin{bmatrix}
    7 & 4 & 2 \\
    1 & 3 & -1 \\
    2 & 6 & -4
\end{bmatrix}
\end{align}

In [14]:
E = np.array([[7, 4, 2],
             [1, 3, -1],
             [2, 6, -4]])

E_T = E.T
E_T

array([[ 7,  1,  2],
       [ 4,  3,  6],
       [ 2, -1, -4]])

In [15]:
E_1 = np.linalg.inv(E)
E_1

array([[ 0.17647059, -0.82352941,  0.29411765],
       [-0.05882353,  0.94117647, -0.26470588],
       [ 0.        ,  1.        , -0.5       ]])

## 3. $|F|$ 를 구하세요. 이 데이터는 어떤 의미가 있나요?

\begin{align}
F = 
\begin{bmatrix}
    2 & -2 & 5 \\
    4 & 1 & 10 \\
    12 & 6 & 30
\end{bmatrix}
\end{align}

In [18]:
F = np.array([[2, -2, 5], 
              [4, 1, 10], 
              [12, 6, 30]])

F2 = np.abs(F)
F2
#의미는 모르겠다..

array([[ 2,  2,  5],
       [ 4,  1, 10],
       [12,  6, 30]])

## 4. 다음 데이터의 covariance, correlation을 구하세요.

- x = [820, 760, 1250, 990, 1080, 1450, 1600]

- y = [0, 1, 7, 1, 0, 6, 4]

In [17]:
x_y = np.array([[820, 760, 1250, 990, 1080, 1450, 1600], 
                [0, 1, 7, 1, 0, 6, 4]])

values, vectors = np.linalg.eig(x_y)
print("\n Eigenvalues: \n", values)
print("\n Eigenvectors: \n", vectors)

#위 데이터로 정사각 데이터를 어떠케 만들지..?

LinAlgError: ignored

## 5. 다음 데이터를 정규화 하세요.

아래 링크를 참조하세요.

<https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html>

In [ ]:
import pandas as pd

data = {"Country": ["England","Wales","Scotland","North Ireland"], 
        "Cheese": [105,103,103,66], 
        "Carcass_Meat": [245,227,242,267], 
        "Other_Meat": [685, 803, 750, 586], 
        "Fish": [147, 160, 122, 93], 
        "Fats_and_Oils": [193, 235, 184, 209], 
        "Sugars": [156, 175, 147, 139], 
        "Fresh_Potatoes": [720, 874, 566, 1033], 
        "Fresh_Veg": [253, 265, 171, 143], 
        "Other_Veg": [488, 570, 418, 355], 
        "Processed_Potatoes": [198, 203, 220, 187], 
        "Processed_Veg": [360, 365, 337, 334], 
        "Fresh_Fruit": [1102, 1137, 957, 674], 
        "Cereals": [1472, 1582, 1462, 1494], 
        "Beverages": [57,73,53,47], 
        "Soft_Drinks": [1374, 1256, 1572, 1506], 
        "Alcoholic Drinks": [375, 475, 458, 135], 
        "Confectionery": [54, 64, 62, 41]}

df = pd.DataFrame(data)

df

Country  Cheese  ...  Alcoholic Drinks  Confectionery
0        England     105  ...               375             54
1          Wales     103  ...               475             64
2       Scotland     103  ...               458             62
3  North Ireland      66  ...               135             41

[4 rows x 18 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler

## 6. 위 데이터에 PCA 를 적용 후 scatterplot을 그리세요.

## 7. 아래 데이터에 대해 k-means clustering을 적용 후, 결과를 그래프로 그리세요.



In [ ]:
points = pd.read_csv('https://ds-lecture-data.s3.ap-northeast-2.amazonaws.com/sc13x/data.csv')
points.head()

x         y
0 -7.846803 -3.421277
1 -3.554323 -6.884729
2 -0.192822 -9.671030
3 -6.401456 -5.223972
4 -0.804026 -9.704457

In [ ]:
points.shape

(200, 2)

# SC 3점 요구사항:
위에서 요구된 사항들을 모두 정확하게 만족하였으며, 아직 시간이 남았다면 아래 2개의 내용들 중 하나를 만족하는 경우 3점을 얻을 수 있습니다.

아래 요구사항들은 모두 optional 임을 다시 한 번 강조합니다. (필수 요구사항이 아닙니다.)

- 6번의 PCA 결과에 대해서 Scree plot을 추가하세요.

- 7번에서 k값을 선택하는 과정을 논리적으로 설명하세요.
